name: Build & Publish Docs to GitHub Pages

on:
#  push:
#    branches:
#      - main
#    paths-ignore:
#      - '**/Package Release Notes.txt'
  workflow_dispatch:

jobs:
  build:
    name: Build Documentation
    uses: ./.github/workflows/_build-docs.yml

  deploy:
    name: Deploy Documentation
    needs: build
    uses: ./.github/workflows/_deploy-docs.yml
