name: Build Documentation Site

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DOTNET_NOLOGO: true
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true # Avoid pre-populating the NuGet package cache

    steps:

      - name: 'Checkout Code'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Required for MinVer to work properly

      - name: 'Setup .NET SDK'
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'

      - run: dotnet tool update -g docfx
        shell: pwsh

      - run: docfx doc/docfx_project/docfx.json
        shell: pwsh

      - name: 'Upload Site Artifacts'
        uses: actions/upload-artifact@v4
        with:
          name: 'Documentation Site'
          path: 'doc/docfx_project/_site/'
          if-no-files-found: error
