name: Build & Publish Docs to GitHub Pages

on: workflow_dispatch

jobs:
  build:
    name: Build Documentation
    uses: ./.github/workflows/_build-docs.yml

  deploy:
    name: Deploy Documentation
    needs: build
    uses: ./.github/workflows/_deploy-docs.yml
