name: Build Aysko iRacing Data API

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    env:
      DOTNET_NOLOGO: true
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true # Avoid pre-populating the NuGet package cache
    
    steps:
      - name: 'Checkout Code'
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Required for MinVer to work properly
      
      - name: 'Setup .NET SDK'
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.x'

      - name: 'Build Solution'
        run: dotnet build -c Release
        working-directory: src

      - name: 'Run Tests'
        run: dotnet test -c Release --no-build --collect:"XPlat Code Coverage"
        working-directory: src

      - name: 'Copy Package to Root'
        shell: pwsh
        run: Get-ChildItem -Path src\*\bin\Release\* -Recurse -Include *.nupkg | Copy-Item -Container:$false

      - name: 'Create Draft Release'
        run: gh release create --draft --prerelease *.nupkg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Upload Artifacts'
        uses: actions/upload-artifact@v2
        with:
          name: NuGet Packages
          path: Aydsko.*.nupkg