name: Build & Create Release (main)

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
  workflow_dispatch:

jobs:
  build:
    name: Build & Test
    uses: ./.github/workflows/_build.yml

  build-docs:
    name: Build Documentation
    uses: ./.github/workflows/_build-docs.yml

  deploy:
    name: Create Draft Release with NuGet Packages
    needs: build
    runs-on: windows-latest

    env:
      DOTNET_NOLOGO: true
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true # Avoid pre-populating the NuGet package cache

    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v2

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3

      - name: Create Draft Release
        shell: pwsh
        # Can't just use wildcard in this command due to https://github.com/cli/cli/issues/5099 so use Get-Item
        run: gh release create --repo "AdrianJSClark/aydsko-iracingdata" --draft --title "${{ github.ref_name }}" --notes-file "..\Release Notes\Package Release Notes.txt" "release-${{ github.ref_name }}" (Get-Item "NuGet Packages/*.nupkg","Documentation Site/*.zip")
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
