name: Publish Aydsko iRacing Data API to NuGet

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    name: 'Publish Package'
    runs-on: ubuntu-latest

    env:
      DOTNET_NOLOGO: true
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true # Avoid pre-populating the NuGet package cache

    steps:

    - name: 'Check Tag Value'
      run: echo ${{ github.event.release.tag_name }}

    - uses: robinraju/release-downloader@v1.10
      name: 'Download Package from Release'
      with:
        repository: 'AdrianJSClark/aydsko-iracingdata'
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: '${{ github.event.release.tag_name }}'
        fileName: '*'
        tarBall: false
        zipBall: false

    - name: 'Expand Documentation Site'
      shell: pwsh
      run: Expand-Archive -Path DocumentationSite.zip -DestinationPath ./_site

    - name: 'Upload Site Artifacts'
      uses: actions/upload-artifact@v4
      with:
        name: 'Documentation Site'
        path: '_site'

    - name: 'Upload to NuGet'
      shell: pwsh
      run: dotnet nuget push *.nupkg --source https://api.nuget.org/v3/index.json --skip-duplicate --api-key ${{ secrets.NUGET_API_KEY }}

  deploy:
    name: Deploy Documentation
    needs: build
    uses: ./.github/workflows/_deploy-docs.yml
