name: 'Test Report'
on:
  workflow_run:
    workflows: ['Build Aydsko iRacing Data API']
    types:
      - completed

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: dorny/test-report@v1
        with:
          artifact: test-results
          name: '.NET Tests'
          path: '**/TestResult/*.trx'
          reporter: 'dotnet-trx'
